exports.seed = async function(knex) {
  await knex('destination').del();
  await knex('destination').insert([
    { id: 1, planet: 'Mars', text: "Perched on the edge of Valles Marineris, New Olympus is the jewel of the Martian frontier. This domed metropolis boasts panoramic views of rust-colored dunes and towering cliffs, perfect for sunset hikes in your exo-suit. Stroll through its gravity gardens, sip solar-brewed cocktails at the Red Horizon Sky Lounge, or take a thrilling rover expedition across the frozen remnants of ancient riverbeds. With its cutting-edge terraforming labs and bustling spaceport, New Olympus is the gateway to the stars—where pioneers and dreamers carve a new destiny on the Red Planet.", 
      price: '14199.99', city: 'New Olympus' },
    { id: 2, planet: 'Europa', text: "Hidden beneath the thick ice shell of Europa, Aquatropolis is a glowing, underwater city suspended in the alien ocean. Bioluminescent corridors wind through its transparent domes, offering breathtaking views of deep-sea geysers and floating luminescent creatures. Visitors can glide through the abyss in personal submarines, enjoy weightless relaxation in Zero-G Thermal Spas, or savor fresh seafood grown in Europa’s hydroponic biofarms. For the truly adventurous, deep-sea expeditions to the mysterious thermal vents below promise an encounter with the unknown.", 
      price: '27599.99', city: 'Aquatropolis' },
    { id: 3, planet: 'Titan', text: "Step into a world unlike any other in Titan Harbor, a city built upon the shimmering methane lakes of Saturn’s largest moon. Protected by a dense, golden-hued atmosphere, Titan’s low gravity allows for effortless strolls across floating platforms and airship tours above hydrocarbon dunes. Visitors can cruise on liquid methane in luxury hover-boats, experience the Skyborne Festival, or take a guided trek to the towering ice cliffs of Xanadu. The breathtaking dual sunset of Titan—one from the distant Sun and the other reflecting off Saturn’s rings—will leave you mesmerized.", 
      price: '32299.99', city: 'Titan Harbor' },
    { id: 4, planet: 'Enceladus', text: "Tucked inside a massive ice cavern warmed by Enceladus’ hydrothermal activity, Crystal Bay is a city of dazzling ice palaces and steamy, geothermal pools. This hidden paradise glows under an artificial sun, while its naturally heated oceans create a tropical escape in the heart of deep space. Relax in Bubble Cove’s warm waters, take an ice-surfing adventure on glacial waves, or venture out to the surface to witness the majestic water plumes shooting into the cosmos. Enceladus offers both serenity and adventure, wrapped in the beauty of eternal ice.", 
      price: '25699.99', city: 'Crystal Bay' },
    { id: 5, planet: 'Ganymede', text: "As the largest moon in the solar system, Ganymede is home to Auroria, a dazzling metropolis built within its own magnetic field—the only moon to have one! Shielded from Jupiter’s intense radiation, this city thrives under artificial auroras that dance across the sky. Explore its crystal caverns, ride hover-bikes across its low-gravity plains, or dine at The Cosmic Spire, a fine-dining restaurant overlooking Jupiter’s Great Red Spot. Whether you're here for relaxation or research, Auroria is a celestial sanctuary unlike any other.", 
      price: '20599.99', city: 'Auroria' },
    { id: 6, planet: 'Callisto', text: "For those seeking both adventure and solitude, Stormhaven on Callisto is the perfect retreat. Built into the moon’s icy cliffs, this city offers panoramic views of Jupiter’s swirling storms while keeping visitors safe from radiation exposure. Guests can traverse the frozen wastelands on magnetized skimmers, stargaze from Echo Observatory, or experience the surreal beauty of the Silent Plains, where the vacuum of space muffles every sound. Stormhaven is the ultimate escape for those who want to stand at the edge of the known world and gaze into the infinite.", 
      price: '13599.99', city: 'Stormhaven' },    
  ]);
};
